// Self-hosts the JEM webfonts. Downloads the woff2 files for Archivo,
// Source Serif 4 and Noto Nastaliq Urdu from Google Fonts (latin subsets,
// plus arabic for Nastaliq) into assets/fonts/, and rewrites
// assets/css/fonts.css as local @font-face rules — so the shipped site
// makes zero third-party requests. Authoring-side only; run once (or
// re-run to refresh):  node _build/fetch-fonts.mjs
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = join(ROOT, 'assets', 'fonts');
// A modern-browser UA is required or Google serves legacy TTF instead of woff2.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

const FAMILIES = [
  { css: 'family=Archivo:wght@400;500;600;700;800;900', name: 'Archivo', slug: 'archivo', subsets: ['latin'] },
  { css: 'family=Source+Serif+4:opsz,wght@8..60,400;8..60,600', name: 'Source Serif 4', slug: 'source-serif-4', subsets: ['latin'] },
  { css: 'family=Noto+Nastaliq+Urdu:wght@400;700', name: 'Noto Nastaliq Urdu', slug: 'noto-nastaliq-urdu', subsets: ['arabic', 'latin'] },
];

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA }, signal: AbortSignal.timeout(30000) });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.text();
}

// Parse the css2 payload into { subset, weight, style, url, unicodeRange } blocks.
function parseFaces(css) {
  const faces = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  let m;
  while ((m = re.exec(css))) {
    const body = m[2];
    const get = (prop) => (body.match(new RegExp(`${prop}:\\s*([^;]+);`)) || [])[1]?.trim();
    faces.push({
      subset: m[1],
      style: get('font-style') || 'normal',
      weight: get('font-weight') || '400',
      stretch: get('font-stretch'),
      url: (body.match(/url\((\S+?)\)/) || [])[1],
      unicodeRange: get('unicode-range'),
    });
  }
  return faces;
}

mkdirSync(FONT_DIR, { recursive: true });

const rules = [];
let failures = 0;

for (const fam of FAMILIES) {
  const css = await fetchText(`https://fonts.googleapis.com/css2?${fam.css}&display=swap`);
  const faces = parseFaces(css).filter((f) => fam.subsets.includes(f.subset));

  // Google serves one variable woff2 per subset when several weights are
  // requested together (verified: the files carry a wght axis). Collapse the
  // per-weight blocks that share a URL into a single @font-face with a
  // font-weight range, so every weight is one declaration and one download.
  const byUrl = new Map();
  for (const f of faces) {
    if (!f.url) continue;
    const g = byUrl.get(f.url) || { ...f, weights: [] };
    g.weights.push(parseInt(f.weight, 10));
    byUrl.set(f.url, g);
  }

  for (const g of byUrl.values()) {
    const file = `${fam.slug}-${g.subset}.woff2`;
    try {
      const res = await fetch(g.url, { headers: { 'User-Agent': UA }, signal: AbortSignal.timeout(60000) });
      if (!res.ok) throw new Error(`${res.status}`);
      writeFileSync(join(FONT_DIR, file), Buffer.from(await res.arrayBuffer()));
      console.log('fetched', file);
    } catch (e) {
      console.error('FAILED', g.url, e.message);
      failures++;
      continue;
    }
    const lo = Math.min(...g.weights);
    const hi = Math.max(...g.weights);
    rules.push(`@font-face {
  font-family: '${fam.name}';
  font-style: ${g.style};
  font-weight: ${lo === hi ? lo : `${lo} ${hi}`};${g.stretch ? `\n  font-stretch: ${g.stretch};` : ''}
  font-display: swap;
  src: url('../fonts/${file}') format('woff2');
  unicode-range: ${g.unicodeRange};
}`);
  }
}

const header = `/* JEM webfonts — self-hosted. Generated by _build/fetch-fonts.mjs; do not
   hand-edit. Archivo (structural) + Source Serif 4 (reading), latin subset,
   and Noto Nastaliq Urdu (RTL Urdu), arabic + latin subsets. Self-hosting
   keeps every page free of third-party requests — a visitor to a hate-crime
   reporting site should leave no trace with any CDN. */
`;
writeFileSync(join(ROOT, 'assets', 'css', 'fonts.css'), header + '\n' + rules.join('\n') + '\n');
console.log(`wrote assets/css/fonts.css — ${rules.length} faces, ${failures} failures`);
if (failures > 0) process.exitCode = 1;
