#!/usr/bin/env python3
"""Build the tracker's world-context layer from Natural Earth 50m countries.

The world layer is unlabeled ground beneath the India layer: neutral land
shapes with faint country outlines, so the map has global context without
foreign place names. India itself is dropped from this layer — the bundled
Government-of-India state geometry (data/india-states.json) is drawn on top
and carries the official external boundary, so no disputed-boundary
rendering from third-party data ever shows.

Usage: python3 scripts/make_world_geo.py <ne_50m_admin_0_countries.json>
Writes data/world.json and data/world.js.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from make_states_geo import simplify_geom
import make_states_geo

ROOT = Path(__file__).resolve().parent.parent

# Coarser than the India layer — this is background context.
make_states_geo.EPS = 0.05
make_states_geo.MIN_RING = 8


def main():
    src = Path(sys.argv[1])
    data = json.loads(src.read_text())
    feats = []
    for f in data["features"]:
        name = f["properties"].get("NAME") or f["properties"].get("name") or ""
        if name == "India":
            continue  # replaced by the official India layer above it
        polys = simplify_geom(f["geometry"])
        if polys:
            feats.append({
                "type": "Feature",
                "properties": {"name": name},
                "geometry": {"type": "MultiPolygon", "coordinates": polys},
            })
    fc = {"type": "FeatureCollection", "features": feats}
    out = ROOT / "data" / "world.json"
    out.write_text(json.dumps(fc, ensure_ascii=False, separators=(",", ":")))
    (ROOT / "data" / "world.js").write_text(
        "/* Generated by scripts/make_world_geo.py — do not edit by hand. */\n"
        "window.JEM_WORLD_GEO = " + json.dumps(fc, ensure_ascii=False, separators=(",", ":")) + ";\n")
    print(f"{len(feats)} countries, {out.stat().st_size // 1024} KB (source {src.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
