#!/usr/bin/env python3
"""Build the tracker's state-choropleth geometry from a districts GeoJSON.

Input: a district-level FeatureCollection with an `st_nm` state-name property
(udit-001/india-maps-data geojson/india.geojson, 2021 boundaries — current
state set incl. Telangana, Ladakh, merged Dadra & Nagar Haveli and Daman & Diu).

Each state's districts are dissolved into one clean polygon (shapely
unary_union — run this script from a venv that has shapely), then rings are
Douglas-Peucker simplified and coordinates rounded, cutting ~4 MB to a few
hundred KB with no internal district edges.

Usage: python3 scripts/make_states_geo.py <districts.geojson>
Writes data/india-states.json and data/india-states.js.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EPS = 0.012          # degrees (~1.2 km) — invisible at country zoom
MIN_RING = 6         # drop islands below this many points after simplify


def dp(points, eps):
    """Iterative Douglas-Peucker on a closed ring (kept closed)."""
    if len(points) < 5:
        return points
    keep = [False] * len(points)
    keep[0] = keep[-1] = True
    # A closed ring starts and ends on the same point, which makes the
    # initial anchor segment degenerate (every distance is zero) — seed a
    # second anchor at the point farthest from the start.
    x0, y0 = points[0]
    m = max(range(1, len(points) - 1),
            key=lambda i: (points[i][0] - x0) ** 2 + (points[i][1] - y0) ** 2)
    keep[m] = True
    stack = [(0, m), (m, len(points) - 1)]
    while stack:
        a, b = stack.pop()
        if b <= a + 1:
            continue
        ax, ay = points[a]
        bx, by = points[b]
        dx, dy = bx - ax, by - ay
        norm = (dx * dx + dy * dy) ** 0.5 or 1e-12
        worst, wi = -1.0, None
        for i in range(a + 1, b):
            px, py = points[i]
            d = abs(dx * (ay - py) - dy * (ax - px)) / norm
            if d > worst:
                worst, wi = d, i
        if worst > eps:
            keep[wi] = True
            stack.append((a, wi))
            stack.append((wi, b))
    return [p for p, k in zip(points, keep) if k]


def simplify_ring(ring):
    ring = dp(ring, EPS)
    if len(ring) < MIN_RING:
        return None
    return [[round(x, 3), round(y, 3)] for x, y in ring]


def simplify_geom(geom):
    polys = geom["coordinates"] if geom["type"] == "MultiPolygon" else [geom["coordinates"]]
    out = []
    for poly in polys:
        rings = [r for r in (simplify_ring(ring) for ring in poly) if r]
        if rings:
            out.append(rings)
    return out


def main():
    src = Path(sys.argv[1])
    data = json.loads(src.read_text())

    # A true geometric dissolve (shapely) merges each state's districts into
    # one clean polygon BEFORE simplification — naive concatenation leaves
    # overlap/XOR holes and internal district edges after simplifying.
    from shapely.geometry import shape, mapping
    from shapely.ops import unary_union

    grouped = {}
    for f in data["features"]:
        grouped.setdefault(f["properties"]["st_nm"], []).append(shape(f["geometry"]))

    states = {}
    for name, geoms in grouped.items():
        merged = unary_union(geoms).buffer(0)
        gj = mapping(merged)
        states[name] = simplify_geom(json.loads(json.dumps(gj)))

    fc = {
        "type": "FeatureCollection",
        "features": [
            {"type": "Feature",
             "properties": {"state": name},
             "geometry": {"type": "MultiPolygon", "coordinates": polys}}
            for name, polys in sorted(states.items())
        ],
    }
    out = ROOT / "data" / "india-states.json"
    out.write_text(json.dumps(fc, ensure_ascii=False, separators=(",", ":")))
    (ROOT / "data" / "india-states.js").write_text(
        "/* Generated by scripts/make_states_geo.py — do not edit by hand. */\n"
        "window.JEM_STATES_GEO = " + json.dumps(fc, ensure_ascii=False, separators=(",", ":")) + ";\n")
    print(f"{len(fc['features'])} states, {out.stat().st_size // 1024} KB "
          f"(source {src.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
